### ISSUE TITLE
Vericoin-2.0.0.1-Linux-64bits.AppImage - Incorrect Total Balance Shown

### ISSUE THREAD

**Issue by ndwcr** [VeriConomy/veribase#3]
Incorrect "Total" balance shown in Appimage GUI

**Expected behavior**

"Total" balance field should display the total number of Vericoin for the wallet.

**Actual behavior**

"Total" balance field shows the available balance (total balance - staking coins)

**To reproduce**

Restart of wallet reproduces the issue.

**System information**

Vericoin-2.0.0.1-Linux-64bits.AppImage

OS = Ubuntu 20.04.2
CPU = Intel Core i5
RAM = 8GB
HDD = SSD

**Comment by mderasse** [comment]
Issue fixed and will be in the next beta version coming this week.
Thank you

**Comment by mderasse** [comment]
The new beta version is out, could you try it and tell me if things are better now ? Thank you !

**Comment by ndwcr** [comment]
Issue appears to be resolved with this new beta.
