### ISSUE TITLE
Vericoin-2.0.0.1-Linux-64bits.AppImage - Incorrect transaction amounts displayed

### ISSUE THREAD

**Issue by ndwcr** [VeriConomy/veribase#4]
Incorrect transaction amounts displayed

**Expected behavior**

Should display staking reward amounts

**Actual behavior**

Block transactions showing instead of staking reward.

**To reproduce**

Restart of wallet reproduces the issue.

**System information**

Vericoin-2.0.0.1-Linux-64bits.AppImage

Vericoin-2.0.0.1-Linux-64bits.AppImage

OS = Ubuntu 20.04.2
CPU = Intel Core i5
RAM = 8GB
HDD = SSD

**Comment by mderasse** [comment]
Issue fixed and will be in the next beta version coming this week.
Thank you

**Comment by mderasse** [comment]
The new beta version is out, could you try it and tell me if things are better now ? Thank you !

**Comment by ndwcr** [comment]
Issue appears to be resolved with new beta.
