### ISSUE TITLE
Estimated staking time for next intrest payment not showing in new version

### ISSUE THREAD

**Issue by ckelly3** [VeriConomy/veribase#5]
#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/vericonomy/veribase/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by mderasse** [comment]
Thanks for the report.
After quick check in the code, it seems that the implementation of that feature could be quick.
I will give it a shot and try to have it before the official release

**Comment by mderasse** [comment]
I nearly finished the implementation, so it should be in the next beta

**Comment by mderasse** [comment]
Feature will be part of the beta that i will release tomorrow
