### ISSUE TITLE
Link to block explorer leads to VRM not VRC-explorer.

### ISSUE THREAD

**Issue by mathiastro** [VeriConomy/veribase#6]
When clicking the Block Explorer link under support and Community resources you are linked to
https://explorer-vrm.vericonomy.com/

Should be: https://explorer-vrc.vericonomy.com/

**Comment by mderasse** [comment]
Thank you for the report. I will look into it asap :)

**Comment by mderasse** [comment]
Fix in the next beta

**Comment by mderasse** [comment]
Beta available on https://files.vericonomy.com/vrc/2.0/releases/2.0.0.3b/
