### ISSUE TITLE
Vericoin 2.0.0.4 Windows: History doesn't show 'Staking Reward' as Type and 'Mined' doesn't show them.

### ISSUE THREAD

**Issue by keijodputt** [VeriConomy/veribase#8]
**Problem**

There's a purely cosmetic issue with the History view in the 2.0.0.4 Wallet, carried over from the previous Beta.
Below the "Filters" view, there are the "Search", "Type", "Amount" and "Date" form fields. 
Going to the Type field you may select from these 4:
![image](https://user-images.githubusercontent.com/9009579/123499072-51908000-d634-11eb-8852-7c5d957bd74f.png)

**Expected behavior**

"Interest" drop-down option and stake records should show in this view, as seen by the previous 1.7.2 release:
For the drop-down item:
![image](https://user-images.githubusercontent.com/9009579/123512919-6992ee80-d68a-11eb-9906-f12485c56918.png)

For the record list:
![image](https://user-images.githubusercontent.com/9009579/123512970-aced5d00-d68a-11eb-889b-3a01e1fd59ed.png)

Problem is within the selection within  the "Type" drop-down: "All", "Received With", "Sent To", "To Yourself", "Mined", and "Other" are present, but "Mined" has the issues that:
-- Neither reads nor behaves as "Interest".
-- It doesn't show the "Staking reward", which would replace the "Interest" field in previous RTM, not even spanning throughout the date range chosen below "Amount", in the "Date" field.
![image](https://user-images.githubusercontent.com/9009579/123513296-bb3c7880-d68c-11eb-9a83-076ee4b52c92.png)

 

**To reproduce**

Some of these steps can be skipped if their requisites are in PASS already. I'm just including them for reference and in case the error can't be reproduced, to make sure all conditions are met.

1- Boot the node where the wallet is located, if it's not powered on yet.
2- Log in to the user holding the wallet, if not logged-in yet.
3- Run the wallet application by ONE of any available means in the Operating system, so that an instance of the process is present for the error to reproduce, again, if the wallet application isn't running, yet.
4- With the wallet running, make sure that:
    a-- The Blockchain is in full-sync with the node.
    b-- There are some staking rewards in your History.
    c-- The chosen tab is the "Browse transaction history"
5- from within the Filters selection, choose "Mined" from the drop-down.
6- Cry.

**System information**

This behavior was detected in the Windows 2.0.0.4 installed package,

The node resides in a Windows virtual machine running 2 cores on an AMD Opteron 4334 processor, the storage is a simple SATA rotating drive, and had no issues running version 2.0.0.3 of the wallet.

The Operating system is vanilla Windows 10 20H2 x64, only purposed for wallet and vault testing.

For the resolution, I'm pretty sure it's just renaming/reattaching the fields together in the source code.

**Comment by mderasse** [comment]
Fixed in the next beta :) Thank you for the bug report
